[package]
name = "chorrent"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = "1.1.0"
tokio = {version = "1", features = ["full"]}
bao-tree = "0.16"
anyhow = "1"
thiserror = "2.0.20"
iroh-tickets = "1"
blake3 = "1"
iroh-gossip = "0.101.0"
serde = { version = "1.0.229", features = ["derive"] }
postcard = "1.1.3"
futures-lite = "2.6.1"
n0-future = "0.3.2"
clap = { version = "4.6.7", features = ["derive"] }
rand = "0.10.2"
base64 = "0.23.1"

[dev-dependencies]
tempfile = "3"
