[package]
name = "chorrent"
description = "Peer-to-peer and swarm file transfer over Iroh/QUIC with verified, chunked downloads"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
iroh.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
bao-tree.workspace = true
thiserror.workspace = true
iroh-tickets.workspace = true
blake3.workspace = true
iroh-gossip.workspace = true
serde.workspace = true
postcard = { workspace = true, features = ["alloc"] }
futures-lite.workspace = true
rand.workspace = true
base64.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
